name: anime_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc_test: ^9.1.7
  built_collection: ^5.1.1
  built_value: ^8.9.2
  chopper: ^8.0.1+1
  chopper_generator: ^8.0.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  injectable: ^2.4.4
  injectable_generator: ^2.6.2
  mockito: ^5.4.4
  mocktail: ^1.0.4
  paginated_list: ^1.2.3

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.2

flutter:
  uses-material-design: true